### ISSUE TITLE
Video duration and day of broadcasting not shown

### ISSUE THREAD

**Issue by FlorianLiers** [AddonScriptorDE/plugin.video.ardmediathek_de#2]
Neither day of broadcasting nor the duration of the videos are determined correctly for videos.

Seems to be an issue with the regular expression for the "mt-airtime" attribute. The current:
'<span class="mt-airtime">\n                    (.+?)\n                    (.+?) min\n            </span>'
is no longer able to parse strings like this:
<span class="mt-airtime">02.01.14 19:35 min</span>

**Comment by AddonScriptorDE** [comment]
See my testing-repo:
http://code.google.com/p/addonscriptorde-beta-repo/downloads/detail?name=repository.addonscriptorde-beta.zip&can=2&q=
Should be available via the xbmc.org soon...
