### ISSUE TITLE
"Dossiers" have an "</a>" at the end of their title

### ISSUE THREAD

**Issue by FlorianLiers** [AddonScriptorDE/plugin.video.ardmediathek_de#3]
If all "Dossiers" are listed, their titles have an "</a>" at the end. Seems to be an issue with an regular expression in method listDossiers.

**Comment by AddonScriptorDE** [comment]
See my testing-repo:
http://code.google.com/p/addonscriptorde-beta-repo/downloads/detail?name=repository.addonscriptorde-beta.zip&can=2&q=
Should be available via the xbmc.org soon...
