### ISSUE TITLE
Only the first page of search results is shown

### ISSUE THREAD

**Issue by FlorianLiers** [AddonScriptorDE/plugin.video.ardmediathek_de#4]
... if you access the second page, a script error is reported. The error is an URLError('no host given') thrown within gutUrl.

If the first search page (e.g., http://www.ardmediathek.de/suche?detail=40&sort=tages&s=tag&inhalt=tv&goto=1) is retrieved correctly, the second page is opened with a wrong URL (http://www.ardmediathek.de/suche?detail=40&amp;s=tages&amp;inhalt=tv&amp;goto=2). This link (with "&amp;" instead of "&") is already given in the first result page.

**Comment by AddonScriptorDE** [comment]
See my testing-repo:
http://code.google.com/p/addonscriptorde-beta-repo/downloads/detail?name=repository.addonscriptorde-beta.zip&can=2&q=
Should be available via the xbmc.org soon...
