### ISSUE TITLE
Configurable video titles

### ISSUE THREAD

**Issue by FlorianLiers** [AddonScriptorDE/plugin.video.ardmediathek_de#5]
It would be nice to have different parts in the video titles. Sometimes, the plain video name is sufficient. However, titles like "Making-Of" or "Folge 109: bla" are not really useful. They should contain the name of the series/show, such as "Brettl-Spitzen: Making-Of" and "Verrückt nach Meer: Folge 109: bla". Because some user may prefer the shorter title, the parts of the title should be configurable.

**Comment by AddonScriptorDE** [comment]
Maybe i will make it configurable...

**Comment by FlorianLiers** [comment]
Well, you could use my legwork https://github.com/FlorianLiers/plugin.video.ardmediathek_de/commit/0ca1f2394f076aae8afb0ea62b812516ffcded85, which incorpurates the configurability.
